services:
  - type: web
    name: alexismarcanbot
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
